export const skillSuggestions = [
  "React",
  "Node.js",
  "Express.js",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Firebase",
  "Flutter",
  "Dart",
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "Git",
  "GitHub",
  "Docker",
  "AWS",
  "Linux",
  "Machine Learning",
  "Artificial Intelligence",
  "Cyber Security",
  "UI/UX Design",
  "Figma"
];

export const interestSuggestions = [
  "Artificial Intelligence",
  "Machine Learning",
  "Cyber Security",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Blockchain",
  "Robotics",
  "Hackathons",
  "Open Source",
  "Competitive Programming",
  "Entrepreneurship",
  "Startups",
  "Photography",
  "Music",
  "Technology",
  "Sports",
  "Travel"
];

export const hobbySuggestions = [
  "Reading",
  "Photography",
  "Traveling",
  "Gaming",
  "Cooking",
  "Music",
  "Drawing",
  "Painting",
  "Writing",
  "Cycling",
  "Hiking",
  "Swimming",
  "Football",
  "Cricket",
  "Badminton",
  "Chess",
  "Coding",
  "Movies"
];